// Generated by CoffeeScript 1.3.1
(function() {
  var LazyLoader, lazy_loader;

  LazyLoader = (function() {
    var isElementVisible, listLowResImages, loadRighRes, lowResImages, updateImages;

    LazyLoader.name = 'LazyLoader';

    lowResImages = [];

    function LazyLoader(cssClass) {
      this.cssClass = cssClass;
      this.updateImages();
    }

    isElementVisible = function(element) {
      return element.getBoundingClientRect().top < window.innerHeight;
    };

    listLowResImages = function(forceFetch) {
      if (forceFetch || this.lowResImages.length === 0) {
        this.lowResImages = document.getElementsByClassName(this.cssClass);
      }
      return this.lowResImages;
    };

    updateImages = function() {
      var img, _i, _len, _ref, _results;
      this.listLowResImages(true);
      _ref = this.lowResImages;
      _results = [];
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        img = _ref[_i];
        if (this.isElementVisible(img)) {
          _results.push(this.loadRighRes(img));
        }
      }
      return _results;
    };

    loadRighRes = function(img) {
      img.className = img.className.replace(this.cssClass, '');
      img.src = img.getAttribute('data-img-src');
      return console.info('loading ' + img.src);
    };

    return LazyLoader;

  })();

  lazy_loader = new LazyLoader('lowResImages');

  window.load = function() {
    var actualPosition;
    lazy_loader.updateImages();
    actualPosition = window.pageYOffset;
    return window.onscroll = function() {
      if (window.pageYOffset > actualPosition) {
        lazy_loader.updateImages();
      }
      return actualPosition = window.pageYOffset;
    };
  };

}).call(this);
